# Robotic Handwriting AI - Main Configuration

# Project Settings
project:
  name: "robotic-handwriting-ai"
  version: "1.0.0"
  description: "AI-powered robotic handwriting system"

# Robot Configuration
robot:
  type: "virtual_7dof"
  name: "WriteBot"
  
  # Kinematic Parameters
  kinematics:
    dof: 7  # Degrees of freedom
    joint_limits:
      - [-180, 180]  # Joint 1 (shoulder pan)
      - [-90, 90]    # Joint 2 (shoulder lift)
      - [-180, 180]  # Joint 3 (shoulder roll)
      - [-150, 0]    # Joint 4 (elbow)
      - [-180, 180]  # Joint 5 (wrist 1)
      - [-90, 90]    # Joint 6 (wrist 2)
      - [-180, 180]  # Joint 7 (wrist 3)
    
    link_lengths: [0.15, 0.30, 0.25, 0.20, 0.10, 0.08, 0.05]  # meters
    max_velocity: [3.14, 3.14, 3.14, 3.14, 6.28, 6.28, 6.28]  # rad/s
    max_acceleration: [10.0, 10.0, 10.0, 10.0, 20.0, 20.0, 20.0]  # rad/s²

  # Hand/Gripper Configuration
  hand:
    type: "dexterous_gripper"
    fingers: 5
    joints_per_finger: 3
    grip_force_range: [0.0, 50.0]  # Newtons
    finger_length: 0.08  # meters

  # End-effector (Pen) Configuration
  pen:
    length: 0.15  # meters
    weight: 0.02  # kg
    tip_radius: 0.001  # meters
    max_pressure: 10.0  # Newtons

# AI Model Configuration
ai_models:
  # Imitation Learning (GAIL)
  gail:
    learning_rate: 0.0003
    batch_size: 64
    buffer_size: 100000
    policy_network:
      hidden_layers: [256, 128, 64]
      activation: "relu"
    discriminator_network:
      hidden_layers: [128, 64, 32]
      activation: "relu"
    
  # Physics-Informed Neural Network (PINN)
  pinn:
    learning_rate: 0.001
    physics_weight: 0.1
    data_weight: 0.9
    network_layers: [128, 64, 32, 16]
    
  # Trajectory Generation
  trajectory:
    model_type: "sigma_lognormal"
    smoothing_factor: 0.1
    min_stroke_length: 0.001  # meters
    max_stroke_length: 0.1   # meters

# Training Configuration
training:
  epochs: 1000
  validation_split: 0.2
  early_stopping_patience: 50
  checkpoint_frequency: 10
  device: "auto"  # auto, cuda, cpu
  
  # Data Augmentation
  augmentation:
    enabled: true
    rotation_range: 5  # degrees
    scale_range: [0.9, 1.1]
    noise_level: 0.01

# Simulation Settings
simulation:
  platform: "mujoco"  # Options: mujoco, pybullet, isaacgym
  physics:
    timestep: 0.001  # seconds
    gravity: [0, 0, -9.81]  # m/s²
    damping: 0.1
  
  rendering:
    width: 1920
    height: 1080
    fps: 60
    background_color: [1.0, 1.0, 1.0]  # White

# Writing Surface Configuration
writing_surface:
  type: "paper"
  dimensions: [0.21, 0.297]  # A4 paper in meters
  position: [0.5, 0.0, 0.0]  # relative to robot base
  orientation: [0, 0, 0]  # roll, pitch, yaw
  friction_coefficient: 0.7

# Handwriting Style Configuration
styles:
  default:
    name: "casual"
    letter_height: 0.005  # meters
    letter_spacing: 0.003  # meters
    word_spacing: 0.008   # meters
    slant_angle: 5        # degrees
    pressure_variation: 0.2
    speed_factor: 1.0
    
  formal:
    name: "formal"
    letter_height: 0.004
    letter_spacing: 0.002
    word_spacing: 0.006
    slant_angle: 0
    pressure_variation: 0.1
    speed_factor: 0.8
    
  artistic:
    name: "artistic"
    letter_height: 0.008
    letter_spacing: 0.004
    word_spacing: 0.012
    slant_angle: 10
    pressure_variation: 0.5
    speed_factor: 0.6

# Data Configuration
data:
  input_formats: ["txt", "json", "csv"]
  output_formats: ["trajectory", "image", "video"]
  
  datasets:
    training_path: "data/training_datasets"
    validation_path: "data/validation_sets"
    raw_data_path: "data/raw_handwriting"
    
  preprocessing:
    normalize_trajectories: true
    filter_noise: true
    resample_rate: 100  # Hz

# Evaluation Metrics
evaluation:
  metrics:
    - "trajectory_similarity"
    - "writing_quality"
    - "speed_consistency"
    - "pressure_control"
    - "style_adherence"
  
  similarity_threshold: 0.9
  quality_threshold: 0.85

# Logging and Monitoring
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/handwriting_ai.log"
  wandb:
    enabled: true
    project: "robotic-handwriting"
    entity: "your-username"

# Performance Settings
performance:
  parallel_workers: 4
  memory_limit: "8GB"
  gpu_memory_fraction: 0.8
  
# Safety and Constraints
safety:
  max_joint_velocity: [3.0, 3.0, 3.0, 3.0, 5.0, 5.0, 5.0]  # rad/s
  max_end_effector_force: 20.0  # Newtons
  workspace_limits:
    x: [0.2, 0.8]  # meters
    y: [-0.3, 0.3]
    z: [0.0, 0.5]
  
  emergency_stop_conditions:
    - "excessive_force"
    - "joint_limit_violation"
    - "workspace_violation"